  version: '3'
    
  services:
    db:
      image: mysql
      restart: always
      command: --default-authentication-plugin=mysql_native_password --mysqlx=0
      env_file: app.env
      ports:
        - "3306:3306"
      volumes:
        - "./db:/var/lib/mysql"
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      env_file: app.env
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db